# Generated by Django 6.0.1 on 2026-05-15 02:03

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fluxo",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        default="", max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "servico",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Serviço"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_debito", "Cartão Débito"),
                            ("cartao_credito", "Cartão Crédito"),
                            ("pix", "PIX"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("a_prazo", "A Prazo"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Tipo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo Financeiro",
                "verbose_name_plural": "Fluxos Financeiros",
                "db_table": "financeiro_fluxo",
                "ordering": ["-data"],
                "indexes": [
                    models.Index(fields=["-data"], name="financeiro__data_754340_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Servicos",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "servico",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Serviço"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_debito", "Cartão Débito"),
                            ("cartao_credito", "Cartão Crédito"),
                            ("pix", "PIX"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("a_prazo", "A Prazo"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pago", "Pago"),
                            ("pendente", "Pendente"),
                            ("cancelado", "Cancelado"),
                            ("estornado", "Estornado"),
                        ],
                        default="pago",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço Financeiro",
                "verbose_name_plural": "Serviços Financeiros",
                "db_table": "financeiro_servicos",
                "ordering": ["-data", "-created_at"],
                "indexes": [
                    models.Index(fields=["-data"], name="financeiro__data_8e2ee2_idx"),
                    models.Index(
                        fields=["status"], name="financeiro__status_b1e60a_idx"
                    ),
                ],
            },
        ),
    ]
